name: Email Digest (Daily)

on:
  schedule:
    # 09:00 AM Asia/Singapore (UTC+8) = 01:00 UTC
    - cron: "0 1 * * *"
  workflow_dispatch: {}

concurrency:
  group: email-digest
  cancel-in-progress: true

jobs:
  run-digest:
    runs-on: ubuntu-latest
    env:
      DISABLE_DIGEST: ${{ secrets.DISABLE_DIGEST || '' }}
      DEBUG: ${{ secrets.DEBUG || '' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          printf '%s' "${{ secrets.GMAIL_CREDENTIALS_JSON }}" > credentials.json
          printf '%s' "${{ secrets.GMAIL_TOKEN_JSON }}" > token.json
      - run: |
          printf "OPENAI_API_KEY=%s\nEMAIL_USERNAME=%s\nEMAIL_APP_PASSWORD=%s\n" \
            "${OPENAI_API_KEY}" "${EMAIL_USERNAME}" "${EMAIL_APP_PASSWORD}" > .env
      - run: python main.py
