name: Email Digest (Daily)

on:
  schedule:
    # 09:00 AM Asia/Singapore (UTC+8) = 01:00 UTC
    - cron: "0 1 * * *"
  workflow_dispatch: {}

concurrency:
  group: email-digest
  cancel-in-progress: true

jobs:
  run-digest:
    runs-on: ubuntu-latest
    env:
      DISABLE_DIGEST: ${{ secrets.DISABLE_DIGEST || '' }}
      DEBUG: ${{ secrets.DEBUG || '' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ⬇️ decode base64 secrets back into JSON files
      - name: Recreate credentials.json and token.json from Secrets (base64)
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS_JSON_B64 }}" | base64 --decode > credentials.json
          echo "${{ secrets.GMAIL_TOKEN_JSON_B64 }}" | base64 --decode > token.json

      # (optional) quick sanity check; safe to remove later
      - name: Inspect token.json (first 20 lines + show control chars)
        run: |
          head -20 token.json || true
          cat -A token.json || true

      - run: |
          printf "OPENAI_API_KEY=%s\nEMAIL_USERNAME=%s\nEMAIL_APP_PASSWORD=%s\n" \
            "${OPENAI_API_KEY}" "${EMAIL_USERNAME}" "${EMAIL_APP_PASSWORD}" > .env

      - run: python main.py
